// This file was generated by Prisma, and handles configuration setup
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Explicitly tell Prisma config to check your local env file
dotenv.config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});