import json
import os
import urllib.request
import urllib.error
import config

def call_groq_api(prompt: str, system_message: str = "You are an expert AI Financial Advisor and Treasury Management Assistant.", api_key: str = None, model: str = None, timeout: int = 15) -> str:
    """
    Sends a completion request to the Groq API endpoint (https://api.groq.com/openai/v1/chat/completions).
    Returns the string text generated by Groq LLM, or None if call fails or API key missing.
    """
    api_key = api_key or os.getenv("GROQ_API_KEY", config.GROQ_API_KEY)
    model = model or os.getenv("GROQ_MODEL", config.GROQ_MODEL)

    if not api_key:
        return None

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_message},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3,
        "max_tokens": 1024
    }

    try:
        req = urllib.request.Request(
            config.GROQ_API_URL,
            data=json.dumps(payload).encode("utf-8"),
            headers=headers,
            method="POST"
        )

        with urllib.request.urlopen(req, timeout=timeout) as response:
            if response.status == 200:
                res_body = json.loads(response.read().decode("utf-8"))
                choices = res_body.get("choices", [])
                if choices:
                    return choices[0].get("message", {}).get("content", "").strip()
    except Exception as e:
        print(f"[Groq AI Advisor] API Call Warning: {str(e)}")
        return None

    return None


def generate_groq_executive_summary(forecasts: list, shortage_alerts: list, api_key: str = None) -> dict:
    """
    Uses Groq AI to generate executive summary commentary and fund health assessment.
    Falls back gracefully if Groq API fails.
    """
    prompt = f"""
Analyze the following financial forecast summary data for our organization's treasury funds:
Fund Forecasts: {json.dumps(forecasts, indent=2)}
Shortage Alerts: {json.dumps(shortage_alerts, indent=2)}

Provide a concise 3-bullet executive summary and overall liquidity health assessment for the Treasurer and Board of Trustees.
Formatting requirement: Return your response strictly as valid JSON with keys:
"executive_narrative": "A professional paragraph summary.",
"key_takeaways": ["bullet 1", "bullet 2", "bullet 3"],
"risk_level": "LOW" or "MEDIUM" or "HIGH"
"""

    ai_response = call_groq_api(prompt, system_message="You are a senior financial analyst and treasury manager.", api_key=api_key)

    if ai_response:
        try:
            # Clean possible markdown codeblock formatting ```json
            clean_str = ai_response.strip()
            if clean_str.startswith("```json"):
                clean_str = clean_str[7:]
            if clean_str.endswith("```"):
                clean_str = clean_str[:-3]
            parsed = json.loads(clean_str.strip())
            parsed["groq_powered"] = True
            return parsed
        except Exception:
            pass

    # Fallback response
    has_high_alerts = any(a.get("severity") == "high" for a in shortage_alerts)
    return {
        "groq_powered": False,
        "executive_narrative": "60-day financial projections indicate stable liquidity across major funds, with automated monitoring active for reserve compliance.",
        "key_takeaways": [
            f"Evaluated {len(forecasts)} active fund balances.",
            f"Detected {len(shortage_alerts)} reserve warnings requiring attention.",
            "Surplus funds maintain strong positive yields for optimal allocation."
        ],
        "risk_level": "HIGH" if has_high_alerts else ("MEDIUM" if shortage_alerts else "LOW")
    }


def refine_recommendations_with_groq(recommendations: list, forecasts: list, api_key: str = None) -> list:
    """
    Enhances recommendation descriptions using Groq AI LLM advice.
    """
    if not recommendations:
        return recommendations

    prompt = f"""
Refine the narrative and financial justification for these automated fund reallocation recommendations:
Recommendations: {json.dumps(recommendations, indent=2)}
Fund Context: {json.dumps(forecasts, indent=2)}

Return a JSON array of refined recommendation objects containing the exact same "id" fields but with enhanced "title" and "description" fields containing professional financial reasoning.
Formatting requirement: Return ONLY a valid JSON array.
"""

    ai_response = call_groq_api(prompt, system_message="You are an expert treasury advisor.", api_key=api_key)

    if ai_response:
        try:
            clean_str = ai_response.strip()
            if clean_str.startswith("```json"):
                clean_str = clean_str[7:]
            if clean_str.endswith("```"):
                clean_str = clean_str[:-3]
            refined_list = json.loads(clean_str.strip())

            # Merge refined fields back
            refined_map = {r["id"]: r for r in refined_list if isinstance(r, dict) and "id" in r}
            for rec in recommendations:
                r_id = rec.get("id")
                if r_id in refined_map:
                    if refined_map[r_id].get("title"):
                        rec["title"] = refined_map[r_id]["title"]
                    if refined_map[r_id].get("description"):
                        rec["description"] = refined_map[r_id]["description"]
                    rec["ai_provider"] = "Groq LLaMA-3.3-70B"
        except Exception as err:
            print(f"[Groq AI Advisor] Refinement Parse Warning: {err}")

    return recommendations


def generate_groq_audit_summary(action: str, status: str, details: dict, api_key: str = None) -> str:
    """
    Generates natural language audit trail log descriptions using Groq AI.
    """
    prompt = f"Summarize this system audit activity into a concise 1-sentence audit log description:\nAction: {action}\nStatus: {status}\nDetails: {json.dumps(details)}"
    ai_desc = call_groq_api(prompt, system_message="You are a system security auditor.", api_key=api_key)
    if ai_desc:
        return ai_desc.replace('"', '').strip()
    return f"{action} completed with status: {status}."
